replicaCount: 1

image:
  name:  "laierr/robin"
  tag: "v0.1"

app:
  name: "running-robin"
  label: "robin"
  requestTimeout: 5
  targetUrl: ""

service:
  type: ClusterIP
  port: 80

ingress: 
  host: localhost

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"