apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: robin-ingress
  labels:
    name: robin-ingress

spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/metrics"
        backend:
          service:
            name: <Service>
            port: 
              number: 80
